Repository j3ro3n/madlibs, pull requests merged in 2022-06, with the labels that each got.

#15 Add footer text
  src/app/component/game.component.ts
  src/app/component/loginForm.component.ts
  src/app/service/localStore.services.ts
  src/app/view/game.component.html
  src/app/view/loginForm.component.html
Labels: beautify

#33 v0.1.0
  backend/server.js
  junk_test_data.md
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/component/game.component.ts
  src/app/component/loginForm.component.ts
  src/app/component/voting.component.ts
  src/app/service/api.services.ts
  src/app/service/localStore.services.ts
  src/app/service/timer.services.ts
  src/app/view/game.component.html
  src/app/view/vote.component.html
  src/app/view/waitingdialog.component.html
Labels: enhancement, beautify, backend-changes

#42 v1.0.0
  backend/server.js
  src/app/app.module.ts
  src/app/component/game.component.ts
  src/app/component/loginForm.component.ts
  src/app/component/voting.component.ts
  src/app/service/api.services.ts
  src/app/view/game.component.html
Labels: enhancement, beautify, backend-changes

#44 Connect via https
  src/app/service/api.services.ts
Labels: bug

#45 Add playerid in anticipation of #43
  src/app/component/game.component.ts
Labels: backend-changes

#48 v1.1.0
  backend/server.js
  src/app/component/game.component.ts
  src/app/component/loginForm.component.ts
  src/app/service/api.services.ts
  src/app/view/game.component.html
  src/app/view/loginForm.component.html
Labels: enhancement, beautify, backend-changes

#52 Update server.js to work with post requests
  backend/server.js
Labels: bug
